[config_files]
meshFile = "input/mesh/channel.toml"
boundaryConditionFile = "input/boundaryConditions/channel.toml"

[fluid]
nu = 1e-2

[time]
timeSteps = 500
CFL = 50.0
SER = false
maxCFL = 1000.0
alphaSER = 1.0

[linearisation]
maxPicardIterations = 5
tolerance = {u = 1e-3, v = 1e-3, p = 1e-3}

[linearSolver]
p = {tolerance = 1e-10, maxIterations = 100, underRelaxation = 0.7}
u = {tolerance = 1e-10, maxIterations = 100, underRelaxation = 0.7}
v = {tolerance = 1e-10, maxIterations = 100, underRelaxation = 0.7}

[convergence]
convergence = {p = 1e-8, u = 1e-8, v = 1e-8}

[output]
filename = "solution"
outputFrequency = 5
createRestartFile = true
