[fluid]
nu = 1e-2

[time]
timeSteps = 500
CFL = 50.0
SER = false
maxCFL = 1000.0
alphaSER = 1.0

[linearisation]
maxPicardIterations = 5
tolerance = {u = 1e-3, v = 1e-3, p = 1e-3}

[linearSolver]
tolerance = {u = 1e-10, v = 1e-10, p = 1e-10}
maxIterations = {u = 100, v = 100, p = 100}
underRelaxation = {u = 0.7, v = 0.7, p = 0.7}

[convergence]
convergence = {p = 1e-8, u = 1e-8, v = 1e-8}

[output]
filename = "lid"
outputFrequency = 5
createRestartFile = true
